export const SET_MOCKDATA = "SET_MOCKDATA";
export const SET_ANALYTICS = "SET_ANALYTICS";
export const SEARCH_MOCKDATA = "SEARCH_MOCKDATA";
export const DELETE_MOCKDATA = "DELETE_MOCKDATA";
export const STARRED_MOCKDATA = "STARRED_MOCKDATA";
export const SET_STARRED_LIST = "SET_STARRED_LIST";
